export type PaletteType = 'ocean' | 'sunset' | 'forest' | 'monochrome' | 'custom';
export type ClassificationMethod = 'equal' | 'quantile' | 'natural';

export interface MapStyle {
  palette: PaletteType;
  customColors?: string[];
  classificationMethod: ClassificationMethod;
  classesCount: number;
  showBorders: boolean;
  borderColor: string;
  borderWidth: number;
  backgroundColor: string;
}

export interface LabelSettings {
  showLabels: boolean;
  fontSize: number;
  fontFamily: string;
  color: string;
  showOnHover: boolean;
  smartLabels: boolean;
}

export interface TitleSettings {
  title: string;
  subtitle: string;
  position: 'top' | 'bottom' | 'none';
  alignment: 'left' | 'center' | 'right';
  color: string;
  size: 'small' | 'medium' | 'large';
}

export interface Annotation {
  id: string;
  x: number;
  y: number;
  text: string;
}

export const PALETTES: Record<PaletteType, string[]> = {
  ocean: ['#f0f9ff', '#bae6fd', '#0ea5e9', '#0284c7', '#0c4a6e'],
  sunset: ['#fefce8', '#fde047', '#f97316', '#dc2626', '#7f1d1d'],
  forest: ['#f0fdf4', '#86efac', '#22c55e', '#15803d', '#14532d'],
  monochrome: ['#f8fafc', '#cbd5e1', '#64748b', '#334155', '#0f172a'],
  custom: ['#f0f9ff', '#0c4a6e'] // Fallback
};

export const DEFAULT_MAP_STYLE: MapStyle = {
  palette: 'ocean',
  classificationMethod: 'quantile',
  classesCount: 5,
  showBorders: true,
  borderColor: 'rgba(255,255,255,0.15)',
  borderWidth: 0.5,
  backgroundColor: '#0b1121'
};

export const DEFAULT_LABEL_SETTINGS: LabelSettings = {
  showLabels: true,
  fontSize: 10,
  fontFamily: 'Inter, sans-serif',
  color: 'rgba(255,255,255,0.8)',
  showOnHover: false,
  smartLabels: true,
};

export const DEFAULT_TITLE_SETTINGS: TitleSettings = {
  title: 'Global Data Visualization',
  subtitle: 'Generated by MapViz AI',
  position: 'top',
  alignment: 'center',
  color: '#ffffff',
  size: 'large',
};
